# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DINKINS
email: ldinkins@live.unc.edu
description: A blog for INLS 161
baseurl: 
url: https://ldinkins.github.io/
twitter_username: lily_elizabethd
github_username:  ldinkins

# Build settings
markdown: kramdown
